# Generated by Django 5.0.2 on 2024-02-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popaNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('POL', 'Politics'), ('ART', 'Art'), ('TECH', 'Technology New'), ('TRIVIA', 'Trivia News')], max_length=32)),
                ('region', models.CharField(choices=[('UK', 'United Kingdom'), ('EU', 'European Union'), ('W', 'World')], max_length=32)),
                ('date', models.DateField(auto_now=True)),
                ('details', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popaNews.author')),
            ],
        ),
    ]
